---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/announcements
  label: Announcements
  create: all
  match: "**/*"
- type: directory
  path: content/annual-reports
  label: Annual reports
  create: all
  match: "**/*"
- type: directory
  path: content/appellate-lawyer-representatives
  label: Appellate lawyer representatives
  create: all
  match: "**/*"
- type: directory
  path: content/attorneys
  label: Attorneys
  create: all
  match: "**/*"
- type: directory
  path: content/bap
  label: Bap
  create: all
  match: "**/*"
- type: directory
  path: content/calendar
  label: Calendar
  create: all
  match: "**/*"
- type: directory
  path: content/cases-of-interest
  label: Cases of interest
  create: all
  match: "**/*"
- type: directory
  path: content/circuit-executive
  label: Circuit executive
  create: all
  match: "**/*"
- type: directory
  path: content/community
  label: Community
  create: all
  match: "**/*"
- type: directory
  path: content/district
  label: District
  create: all
  match: "**/*"
- type: directory
  path: content/efiling
  label: Efiling
  create: all
  match: "**/*"
- type: directory
  path: content/employment
  label: Employment
  create: all
  match: "**/*"
- type: directory
  path: content/en-banc
  label: En banc
  create: all
  match: "**/*"
- type: directory
  path: content/form-test
  label: Form test
  create: all
  match: "**/*"
- type: directory
  path: content/forms
  label: Forms
  create: all
  match: "**/*"
- type: document
  path: content/federal-public-defender-vacancy-announcements/index.html
  label: FPD Vacancies
- type: directory
  path: content/general
  label: General
  create: all
  match: "**/*"
- type: directory
  path: content/guides
  label: Guides
  create: all
  match: "**/*"
- type: directory
  path: content/hr
  label: Hr
  create: all
  match: "**/*"
- type: directory
  path: content/information
  label: Information
  create: all
  match: "**/*"
- type: directory
  path: content/judgeship
  label: Judgeship
  create: all
  match: "**/*"
  exclude: Judgeship
  templates:
  - judgeship
- type: directory
  path: content/library
  label: Library
  create: all
  match: "**/*"
- type: directory
  path: content/judicial-council
  label: Judicial council
  create: all
  match: "**/*"
- type: directory
  path: content/news-media
  label: News media
  create: all
  match: "**/*"
- type: directory
  path: content/lawyer-representatives
  label: Lawyer representatives
  create: all
  match: "**/*"
- type: directory
  path: content/media
  label: Media
  create: all
  match: "**/*"
- type: directory
  path: content/mediation
  label: Mediation
  create: all
  match: "**/*"
- type: directory
  path: content/misconduct
  label: Misconduct
  create: all
  match: "**/*"
- type: directory
  path: content/newsletters
  label: Newsletters
  create: all
  match: "**/*"
- type: directory
  path: content/ninth-circuit-news
  label: Ninth circuit news
  create: all
  match: "**/*"
- type: directory
  path: content/rotator
  label: Rotator
  create: documents
  match: "**/*"
  exclude: _index.html
  templates:
  - rotator
- type: directory
  path: content/rss
  label: Rss
  create: all
  match: "**/*"
- type: directory
  path: content/rules
  label: Rules
  create: all
  match: "**/*"
- type: directory
  path: content/search-results
  label: Search results
  create: all
  match: "**/*"
- type: directory
  path: content/unk
  label: Unk
  create: all
  match: "**/*"
- type: directory
  path: content/pending-execution-dates
  label: Pending execution dates
  create: all
  match: "**/*"
- type: directory
  path: content/probono
  label: Probono
  create: all
  match: "**/*"
- type: directory
  path: content/workplace
  label: Workplace
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
